apiVersion: v1
appVersion: 2.7.1
description: A Helm chart for Docker Registry
home: https://hub.docker.com/_/registry/
icon: https://partner-charts.rancher.io/assets/logos/alex-test1.png
kubeVersion: 1.18 - 1.21
maintainers:
- email: devin@canterberry.cc
  name: Devin Canterberry
  url: https://canterberry.cc/
name: docker-registry
sources:
- https://github.com/docker/distribution-library-image
version: 1.12.1+up1.12.0
